import { createHash, randomBytes } from 'node:crypto';
import { generateKeyPair, SignJWT, createLocalJWKSet, exportJWK } from 'jose';
import {createProviders} from '/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/server/auth/providers.ts';
const rsa=await generateKeyPair('RS256'), ec=await generateKeyPair('ES256');
const c={provider:'google' as const,surface:'web' as const,nonce:randomBytes(32).toString('base64url'),state:randomBytes(32).toString('base64url'),bindingHash:createHash('sha256').update(randomBytes(32)).digest('hex')};
let redeemed='';
const jwt=await new SignJWT({sub:'synthetic-sub',nonce:c.nonce,email:'a@example.test',email_verified:true}).setProtectedHeader({alg:'RS256'}).setAudience('google.web').setIssuer('https://accounts.google.com').setExpirationTime('5m').sign(rsa.privateKey);
const providers=createProviders({siteUrl:'https://erg.test',apple:{nativeClientId:'native.app',webClientId:'web.app',teamId:'TEAM',keyId:'KEY',key:ec.privateKey},google:{nativeClientId:'google.native',webClientId:'google.web',clientSecret:'synthetic'}},{googleKeys:createLocalJWKSet({keys:[await exportJWK(rsa.publicKey)]}),fetch:async(_url,init)=>{redeemed=new URLSearchParams(String(init?.body)).get('code_verifier')!;return Response.json({id_token:jwt});}});
const first=new URL(await providers.authorizationUrl(c));
const second=new URL(await providers.authorizationUrl({...c,nonce:randomBytes(32).toString('base64url')}));
await providers.verify(c,{state:c.state,authorizationCode:'synthetic'});
const apple=new URL(await providers.authorizationUrl({...c,provider:'apple'}));
console.log(JSON.stringify({verifierLength:redeemed.length,verifierSyntax:/^[A-Za-z0-9_-]{43}$/.test(redeemed),challengeMatchesRedemption:createHash('sha256').update(redeemed).digest('base64url')===first.searchParams.get('code_challenge'),newStageDifferentChallenge:second.searchParams.get('code_challenge')!==first.searchParams.get('code_challenge'),appleHasPKCE:apple.searchParams.has('code_challenge'),appleResponseMode:apple.searchParams.get('response_mode')}));
