import request from 'supertest';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { createDb } from '/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/server/db/index.ts';
import { createAttempts } from '/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/server/auth/attempts.ts';
import { createFrontDoorRoutes } from '/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/server/auth/frontDoorRoutes.ts';
import { createApp } from '/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/server/app.ts';
import { createSessionStore } from '/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/server/auth/sessions.ts';
import { baseDeps } from '/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/server/testDeps.ts';
const {pool,db}=createDb('postgres://postgres:review@127.0.0.1:62918/postgres');
await migrate(db,{migrationsFolder:'/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/drizzle'});
const attempts=createAttempts(pool);await attempts.sweep();
const sessions=createSessionStore(db);
const providers={available:()=>true,authorizationUrl:async()=> 'https://apple.test/auth',verify:async()=>({sub:'new-sub',email:'rower@example.test',emailVerified:true,name:'Rower',grant:{clientId:'web.app',refreshToken:'synthetic-grant'}})};
let readCount=0;let releaseFirst!:()=>void;let releaseSecond!:()=>void;
const bothRead=new Promise<void>(r=>releaseFirst=r);const firstFinished=new Promise<void>(r=>releaseSecond=r);
const guarded={...attempts,read:async(...args:Parameters<typeof attempts.read>)=>{const a=await attempts.read(...args);readCount++;if(readCount===1)await bothRead;else if(readCount===2){releaseFirst();await firstFinished;}return a;}};
const routes=createFrontDoorRoutes({attempts:guarded,providers:providers as any,sessions,siteUrl:'https://erg.test'});
const app=createApp(baseDeps({siteUrl:'https://erg.test',sessions,frontDoor:{...routes,attempts,providers,close:()=>{}} as any}));
const begin=await request(app).post('/api/auth/web/attempts').set('Origin','https://erg.test').send({purpose:'signin',provider:'apple'});
const binding=begin.headers['set-cookie'][0].split(';')[0];const body={state:begin.body.state,code:'synthetic-code',id_token:'synthetic-token'};
const post=()=>request(app).post('/api/auth/apple/callback').set('Origin','https://appleid.apple.com').set('Cookie',binding).type('form').send(body).then(r=>r);
const first=post();const second=post();const r1=await first;
console.log(JSON.stringify({afterWinner:{location:r1.headers.location,rows:(await pool.query('SELECT stage,version,apple_refresh_token IS NOT NULL AS grant FROM auth_attempts')).rows}}));
releaseSecond();const r2=await second;
console.log(JSON.stringify({afterLoser:{location:r2.headers.location,rows:(await pool.query('SELECT stage,version FROM auth_attempts')).rows}}));
await pool.end();
