-- Phase JR PR 1 (spec `docs/superpowers/specs/2026-08-24-just-row-design.md`
-- rev 4, "Stored shape"): `workout_type` becomes NULLABLE so a FREE ROW — a
-- Just Row, where the rower chose no workout — can say the true thing:
-- no intensity was prescribed. A sentinel string was rejected because it
-- puts a non-value in the column and makes every future
-- `WHERE workout_type = …` a trap.
--
-- Loosening only, no data touched, nothing else moves:
--   * `workout_type` is plain `text`, NOT the `workout_type` pgEnum (that
--     types `workouts.type`) — so no `ALTER TYPE`, and no collision with
--     the `ended_by` enum work in flight on other branches.
--   * The column carries no index, no CHECK and no FK (`0001_tan_thunderball`
--     :36,44,74-78); the only `session_logs` index is on `user_id`.
--   * Every existing row keeps its value. Readers were already tolerant of
--     drift here (`Plan.tsx`'s `rowedType`), and PR 1 ships the null-aware
--     read side in the same change — the same R-A ordering `0009` used for
--     `held`/`pain`.
--
-- REGENERATE BEFORE MERGE. PRs #248 and #249 both mint index 0017 against a
-- journal head of 16; whichever lands first takes it. This file exists now
-- only so the branch is testable — a null cannot be inserted without it.
ALTER TABLE "session_logs" ALTER COLUMN "workout_type" DROP NOT NULL;