-- Phase JR PR 1 (spec `docs/superpowers/specs/2026-08-24-just-row-design.md`
-- rev 4, "Stored shape"): `workout_type` becomes NULLABLE so a FREE ROW — a
-- Just Row, where the rower chose no workout — can say the true thing: no
-- intensity was prescribed. A sentinel string was rejected because it puts
-- a non-value in the column and makes every future
-- `WHERE workout_type = …` a trap.
--
-- Loosening only, no data touched, nothing else moves:
--   * `workout_type` here is plain `text`, NOT the `workout_type` pgEnum
--     (that types `workouts.type`) — so no `ALTER TYPE`, and no interaction
--     with the `ended_by` enum work that landed as 0017.
--   * The column carries no index, no CHECK and no FK
--     (`0001_tan_thunderball`:36,44,74-78); the only `session_logs` index is
--     on `user_id`.
--   * Every existing row keeps its value. Readers were already tolerant of
--     drift here (`Plan.tsx`'s `rowedType`), and PR 1 ships the null-aware
--     read side in the same change — the same R-A ordering `0009` used for
--     `held`/`pain`.
--
-- Index 0019, and the THIRD regeneration of this file: #248 took 0017 and
-- #249 took 0018 while this branch was open. Both have merged, so there is
-- no known claimant ahead of it now — but check `gh pr list` for a drizzle
-- file before merging rather than trusting this sentence.
ALTER TABLE "session_logs" ALTER COLUMN "workout_type" DROP NOT NULL;