import fs from 'node:fs';import pg from 'pg';import {drizzle} from 'drizzle-orm/node-postgres';import {migrate} from 'drizzle-orm/node-postgres/migrator';import assert from 'node:assert/strict';
const mutant=process.argv.includes('--mutant');const {createAttempts}=await import(mutant?'./mutant/app/server/auth/attempts.ts':'./source/app/server/auth/attempts.ts');const db=mutant?'discard_held_mutant':'discard_held';const admin=new pg.Pool({connectionString:'postgres://postgres:dev@localhost:5434/postgres'});await admin.query('CREATE DATABASE '+db);await admin.end();
const uri='postgres://postgres:dev@localhost:5434/'+db;const pool=new pg.Pool({connectionString:uri,max:10});await migrate(drizzle(pool),{migrationsFolder:'/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/drizzle'});const a=createAttempts(pool);await a.sweep();const uid=(await pool.query("insert into users(google_sub,email,name) values('g1','rower@example.test','Rower') returning id")).rows[0].id;const sid=(await pool.query("insert into sessions(user_id,token_hash,expires_at) values($1,'token',now()+interval '1 day') returning id",[uid])).rows[0].id;
const out:any={mutant,cases:[]};
for(const purpose of ['signin','link'] as const){
 const x=await a.begin({purpose,surface:'native',targetProvider:'apple',...(purpose==='link'?{originalSessionId:sid}:{})});const claimed=await a.claim(x.attempt);
 let open!:()=>void;const paused=new Promise<void>(r=>open=r);let ready!:()=>void;const reached=new Promise<void>(r=>ready=r);let armed=true;
 const winnerPool=new pg.Pool({connectionString:uri,application_name:'discard_winner',max:1});winnerPool.on('connect',client=>{const orig=client.query.bind(client);client.query=async function(q:any,p?:any){if(armed&&q==='COMMIT'){armed=false;ready();await paused;}return orig(q,p);}as any;});
 const winner=createAttempts(winnerPool).accept(claimed,{sub:purpose==='signin'?'new-user':'g1',email:'rower@example.test',emailVerified:true,name:'Rower',...(purpose==='signin'?{grant:{clientId:'native',refreshToken:'retained-synthetic-grant'}}:{})});await reached;
 const start=performance.now();let settled=false;const discard=a.discard(claimed).finally(()=>settled=true);let waits:any[]=[];
 for(let i=0;i<100;i++){waits=(await pool.query("select pid,wait_event_type,wait_event,query from pg_stat_activity where datname=current_database() and wait_event_type='Lock'")).rows;if(waits.length)break;await new Promise(r=>setTimeout(r,10));}
 const settledBeforeCommit=settled;open();const winnerResult=await winner;const deleted=await discard;const rows=(await pool.query('select stage,version,apple_refresh_token from auth_attempts where id=$1',[claimed.id])).rows;
 out.cases.push({purpose,waits,settledBeforeCommit,discardDeleted:deleted,winnerStage:winnerResult.attempt?.stage,winnerVersion:winnerResult.attempt?.version,after:rows,elapsedMs:performance.now()-start});await winnerPool.end();
}
// Deleting a child must not acquire the parent lock held by another transaction.
const link=await a.begin({purpose:'link',surface:'native',targetProvider:'apple',originalSessionId:sid});const hold=await pool.connect();await hold.query('BEGIN');await hold.query('SELECT id FROM sessions WHERE id=$1 FOR UPDATE',[sid]);const t=performance.now();let timedOut=false;const timer=setTimeout(()=>timedOut=true,1000);const childDeleted=await a.discard(link.attempt);clearTimeout(timer);out.parentLock={childDeleted,timedOut,elapsedMs:performance.now()-t};await hold.query('ROLLBACK');hold.release();
await pool.end();fs.writeFileSync('/tmp/apple-dba-discard/'+(mutant?'held-mutant.json':'held.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
for(const r of out.cases){assert.equal(r.settledBeforeCommit,false);assert.ok(r.waits.length>0);assert.equal(r.discardDeleted,false,'stale discard must preserve the winner');assert.equal(r.after.length,1);assert.equal(r.after[0].stage,r.winnerStage);assert.equal(r.after[0].version,r.winnerVersion);if(r.purpose==='signin')assert.equal(r.after[0].apple_refresh_token,'retained-synthetic-grant');}assert.equal(out.parentLock.childDeleted,true);assert.equal(out.parentLock.timedOut,false);
