import fs from 'node:fs';import pg from 'pg';import {drizzle} from 'drizzle-orm/node-postgres';import {migrate} from 'drizzle-orm/node-postgres/migrator';import assert from 'node:assert/strict';import {createAttempts} from './source/app/server/auth/attempts.ts';
const pool=new pg.Pool({connectionString:'postgres://postgres:dev@localhost:5434/postgres',max:1});
await migrate(drizzle(pool),{migrationsFolder:'/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/drizzle'});await pool.query('SET max_parallel_workers_per_gather=0');await pool.query('ALTER SYSTEM SET full_page_writes=off');await pool.query('SELECT pg_reload_conf()');
const out:any={environment:(await pool.query("select version(),current_setting('work_mem') work_mem,current_setting('shared_buffers') shared_buffers,current_setting('jit') jit,current_setting('max_parallel_workers_per_gather') parallelism,current_setting('full_page_writes') full_page_writes")).rows[0],scales:[]};
let capture=false;let recorded:any;const orig=pool.query.bind(pool);pool.query=async function(q:any,p?:any){if(capture&&String(q).startsWith('DELETE FROM auth_attempts WHERE id=$1 AND binding_hash=$2 AND surface=$3 AND purpose=$4'))recorded={sql:q,parameters:p};return orig(q,p);}as any;
for(const n of [5,1000,100000,1000000]){
 await pool.query('TRUNCATE users,auth_attempts CASCADE');await pool.query("INSERT INTO users(id,google_sub,email,name) SELECT md5('u'||i)::uuid,'g'||i,'rower'||i||'@example.test','Rower '||i FROM generate_series(1,5)i");
 await pool.query("INSERT INTO sessions(id,user_id,token_hash,expires_at) SELECT md5('s'||i)::uuid,md5('u'||(1+i%5))::uuid,md5('token'||i),now()+interval '60 days' FROM generate_series(1,$1::int)i",[n]);
 await pool.query("INSERT INTO auth_attempts(binding_hash,surface,purpose,target_provider,existing_provider,stage,version,state,nonce,original_session_id,expires_at) SELECT repeat('b',64),'native','link','apple','google','reauth_authorize',1,md5('lstate'||i),md5('lnonce'||i),md5('s'||i)::uuid,now()+interval '5 minutes' FROM generate_series(1,$1::int)i",[n]);
 await pool.query("INSERT INTO auth_attempts(binding_hash,surface,purpose,target_provider,stage,version,state,nonce,expires_at) SELECT repeat('b',64),'web','signin','apple','authorize',1,md5('astate'||i),md5('anonce'||i),now()+interval '5 minutes' FROM generate_series(1,511)i");
 const a=createAttempts(pool);await a.sweep();const sign=await a.begin({purpose:'signin',surface:'native',targetProvider:'apple'});const sid=(await pool.query('select id from sessions limit 1')).rows[0].id;const link=await a.begin({purpose:'link',surface:'native',targetProvider:'apple',originalSessionId:sid});await pool.query('VACUUM ANALYZE auth_attempts');
 const row:any={links:n,counts:(await pool.query("select (select count(*) from users) users,(select count(*) from sessions) sessions,(select count(*) from auth_attempts where purpose='signin') signin,(select count(*) from auth_attempts where purpose='link') link")).rows[0],cases:[]};out.scales.push(row);
 for(const [name,expected] of [['matching_signin',sign.attempt],['matching_link',link.attempt],['stale_stage',{...sign.attempt,stage:'exchanging'}],['stale_version',{...sign.attempt,version:2}],['stale_binding',{...sign.attempt,bindingHash:'wrong'}]] as any[]){
  const runs=[];for(let i=0;i<6;i++){await pool.query('BEGIN');capture=true;const t=performance.now();const deleted=await a.discard(expected);runs.push(performance.now()-t);capture=false;assert.equal(deleted,name.startsWith('matching'));await pool.query('ROLLBACK');}
  await pool.query('BEGIN');const plan=(await pool.query('EXPLAIN(ANALYZE,BUFFERS,WAL,FORMAT JSON) '+recorded.sql,recorded.parameters)).rows[0]['QUERY PLAN'];await pool.query('ROLLBACK');row.cases.push({name,...recorded,runs,medianMs:runs.slice(1).sort((a,b)=>a-b)[2],plan});
 }
 fs.writeFileSync('/tmp/apple-dba-discard/measure.json',JSON.stringify(out,null,2));console.log(JSON.stringify({n,cases:row.cases.map((r:any)=>({name:r.name,medianMs:r.medianMs,execMs:r.plan[0]['Execution Time'],wal:r.plan[0].Plan['WAL Bytes']}))}));
}
await pool.query('ALTER SYSTEM RESET full_page_writes');await pool.query('SELECT pg_reload_conf()');await pool.end();
