import fs from 'node:fs';import pg from 'pg';import {drizzle} from 'drizzle-orm/node-postgres';import {migrate} from 'drizzle-orm/node-postgres/migrator';import {createAttempts} from '/tmp/apple-dba-discard/source/app/server/auth/attempts.ts';
const root='/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app';
const admin=new pg.Pool({connectionString:'postgres://postgres:dev@localhost:5434/postgres'});await admin.query('CREATE DATABASE apple_dba_discard_regression');await admin.end();
const url='postgres://postgres:dev@localhost:5434/apple_dba_discard_regression';const pool=new pg.Pool({connectionString:url});await migrate(drizzle(pool),{migrationsFolder:root+'/drizzle'});
const uid=(await pool.query("insert into users(google_sub,email,name) values('g','r@example.test','Rower') returning id")).rows[0].id;const sid=(await pool.query("insert into sessions(user_id,token_hash,expires_at) values($1,'token',now()+interval '1 day') returning id",[uid])).rows[0].id;
const a=createAttempts(pool);await a.sweep();let x=await a.begin({surface:'native',purpose:'link',targetProvider:'apple',originalSessionId:sid});
let release!:()=>void;const pause=new Promise<void>(r=>release=r);let reached!:()=>void;const ready=new Promise<void>(r=>reached=r);
const claimPool=new pg.Pool({connectionString:url,application_name:'dba_claim'});claimPool.on('connect',(client)=>{const orig=client.query.bind(client);client.query=async function(q:any,p:any){const r=await orig(q,p);if(typeof q==='string'&&q.includes('FROM auth_attempts')&&q.endsWith('FOR UPDATE')){reached();await pause;}return r;} as any;});
const claimA=createAttempts(claimPool);const started=performance.now();const claim=claimA.claim(x.attempt).then(v=>({ok:true,stage:v.stage}),e=>({ok:false,code:e.code,message:e.message}));await ready;
const replacement=a.begin({surface:'native',purpose:'link',targetProvider:'apple',originalSessionId:sid}).then(v=>({ok:true,id:v.attempt.id}),e=>({ok:false,code:e.code,message:e.message}));
let waits=[];for(let i=0;i<100;i++){const r=await pool.query("select pid,application_name,wait_event_type,wait_event,query from pg_stat_activity where datname=current_database() and wait_event_type='Lock'");if(r.rowCount){waits=r.rows;break;}await new Promise(r=>setTimeout(r,10));}
release();const deadlock={waits,result:await Promise.all([claim,replacement]),elapsedMs:performance.now()-started};console.log(JSON.stringify({deadlock},null,2));
// Exact-session revocation: held uncommitted DELETE must force the real claim to reject after commit.
x=await a.begin({surface:'native',purpose:'link',targetProvider:'apple',originalSessionId:sid});const hold=await pool.connect();await hold.query('BEGIN');await hold.query('DELETE FROM sessions WHERE id=$1',[sid]);const start=performance.now();let settled=false;const revoked=a.claim(x.attempt).then(v=>({ok:true}),e=>({ok:false,code:e.code})).finally(()=>settled=true);await new Promise(r=>setTimeout(r,100));const before=settled;await hold.query('COMMIT');hold.release();const session={settledBeforeCommit:before,result:await revoked,elapsedMs:performance.now()-start};
// Subject conflict: pending signup must wait for a held winner and preserve that winner.
let s=await a.begin({surface:'native',purpose:'signin',targetProvider:'apple'});let c=await a.claim(s.attempt);let p=await a.accept(c,{sub:'race-sub',email:'new@example.test',emailVerified:true,name:'New',grant:{clientId:'native',refreshToken:'grant'}});const h=await pool.connect();await h.query('BEGIN');const winner=(await h.query("insert into users(apple_sub,email,name) values('race-sub','winner@example.test','Winner') returning id")).rows[0].id;settled=false;const confirmed=a.confirm(p.attempt!).then(v=>({ok:true,user:v.signedIn?.user}),e=>({ok:false,code:e.code})).finally(()=>settled=true);await new Promise(r=>setTimeout(r,100));const subjectBefore=settled;await h.query('COMMIT');h.release();const subject={settledBeforeCommit:subjectBefore,winner,result:await confirmed};
fs.writeFileSync('/tmp/apple-dba-discard/original-deadlock-replay.json',JSON.stringify({deadlock,session,subject},null,2));await claimPool.end();await pool.end();
