import fs from 'node:fs';import pg from 'pg';import {createAttempts} from '/Users/james/projects/github/jamesawesome/Ergomatic/.claude/worktrees/wave-a-apple-server-paste/app/server/auth/attempts.ts';
const pool=new pg.Pool({connectionString:'postgres://postgres:dev@localhost:5434/postgres'});const out:any={};
await pool.query('set max_parallel_workers_per_gather=0');await pool.query('alter system set full_page_writes=off');await pool.query('select pg_reload_conf()');
for(const count of [512,1000000]){
 await pool.query('BEGIN');await pool.query("UPDATE auth_attempts SET created_at=now()-interval '10 minutes',expires_at=now()-interval '1 minute' WHERE id IN (SELECT id FROM auth_attempts LIMIT $1)",[count]);const q='DELETE FROM auth_attempts WHERE expires_at<=now()';const p=await pool.query('EXPLAIN(ANALYZE,BUFFERS,WAL,FORMAT JSON) '+q);out['expiry'+count]={sql:q,plan:p.rows[0]['QUERY PLAN']};await pool.query('ROLLBACK');
}
// Index overhead on controlled clones. Source tables and constraints unchanged.
for(const type of ['anon','link','grant','user']){
 const table=type==='grant'?'apple_grants':type==='user'?'users':'auth_attempts';let col='',values='';
 if(type==='anon'||type==='link'){col='id,binding_hash,surface,purpose,target_provider,existing_provider,stage,version,state,nonce,original_session_id,expires_at';values=`gen_random_uuid(),repeat('b',64),'native','${type==='anon'?'signin':'link'}','apple',${type==='anon'?'null':"'google'"},'${type==='anon'?'authorize':'reauth_authorize'}',1,md5(i::text),md5('n'||i),${type==='anon'?'null':'gen_random_uuid()'},now()+interval '5 minutes'`;}
 else if(type==='grant'){col='user_id,client_id,refresh_token';values="gen_random_uuid(),'haus.waffle.ergomatic',repeat('r',512)";}
 else {col='apple_sub,email,name';values="'sub'||i,'rower'||i||'@example.test','Rower'";}
 const rows=[];for(const indexed of [false,true]){await pool.query('BEGIN');await pool.query(`CREATE TABLE dba_write (LIKE ${table} INCLUDING ${indexed?'ALL':'DEFAULTS'})`);const q=`INSERT INTO dba_write(${col}) SELECT ${values} FROM generate_series(1,1000)i`;const ex=await pool.query('EXPLAIN(ANALYZE,BUFFERS,WAL,FORMAT JSON) '+q);rows.push({indexed,sql:q,plan:ex.rows[0]['QUERY PLAN']});await pool.query('ROLLBACK');}out['indexWal_'+type]=rows;
}
const hold=await pool.connect();await hold.query('BEGIN');await hold.query('ALTER TABLE users ADD COLUMN dba_temp text');const start=performance.now();let settled=false;const reader=pool.query('SELECT count(*) FROM users').then(v=>{settled=true;return v.rows[0]});await new Promise(r=>setTimeout(r,100));out.migrationBlocking={settledBeforeCommit:settled,waits:(await pool.query("select wait_event_type,wait_event,query from pg_stat_activity where datname=current_database() and wait_event_type='Lock'")).rows};await hold.query('ROLLBACK');hold.release();out.migrationBlocking.result=await reader;out.migrationBlocking.elapsedMs=performance.now()-start;
await pool.query('BEGIN');await pool.query('DROP TABLE auth_attempts,apple_grants;ALTER TABLE users DROP COLUMN apple_sub');out.schemaReversal={ok:true,remainingUsers:(await pool.query('SELECT count(*) FROM users')).rows[0],nullGoogle:(await pool.query('SELECT count(*) FROM users WHERE google_sub IS NULL')).rows[0]};await pool.query('ROLLBACK');
await pool.query('alter system reset full_page_writes');await pool.query('select pg_reload_conf()');await pool.end();fs.writeFileSync('/tmp/apple-dba-plan/extra.json',JSON.stringify(out,null,2));console.log('extra completed');
